# NB3 — Huấn luyện DPO (notebook chính)

**Công nghệ:** TRL 1.13 `DPOTrainer`, LoRA mới trên mô hình SFT đã gộp, β=0.1, lr=5e-6.

> **Mục tiêu:** huấn luyện adapter DPO, vẽ **riêng** hai đường `rewards/chosen` và
> `rewards/rejected` trên cả tập huấn luyện và tập held-out, rồi tự chẩn đoán xem margin
> tăng theo kiểu nào (NB0 §5).

**Ba thay đổi so với lab cũ, đều ảnh hưởng tới kết quả:**
1. **Mô hình tham chiếu (reference) = mô hình SFT.** Lab cũ chồng LoRA DPO lên LoRA SFT rồi để TRL tắt
   adapter để lấy reference, tức là so với *mô hình gốc*. Ở đây mô hình đang học (policy) là
   `models/sft-merged` + LoRA mới (khởi tạo bằng 0), và
   `precompute_ref_log_probs=True` chấm mọi cặp trước bước cập nhật đầu tiên.
2. **lr = 5e-6.** 5e-7 là mức cho tinh chỉnh toàn bộ; với LoRA và ~100 bước, reward gần như đứng yên.
3. **Eval held-out.** Cặp eval không trùng câu hỏi với huấn luyện (NB2).

In [1]:
import sys
import time
import os
from contextlib import nullcontext
from pathlib import Path

ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / "lab22" / "config.py").exists())
sys.path.insert(0, str(ROOT))

import unsloth  # noqa: F401
import torch

from lab22 import config as C
from lab22 import data as D
from lab22 import modeling as MD

assert torch.cuda.is_available(), "DPO needs a CUDA GPU. See HARDWARE-GUIDE.md."
assert C.SFT_MERGED.exists(), f"Run NB1 first: {C.SFT_MERGED} missing"
assert (C.PREF_DIR / "train.parquet").exists(), "Run NB2 first"
C.ensure_dirs()
print(C.summary())

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/opt/day22-venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

🦥 Unsloth Zoo will now patch everything to make training faster!

COMPUTE_TIER=T4 base=Qwen/Qwen3-0.6B max_len=768 seed=42
SFT saillab/alpaca-vietnamese-cleaned[:1000]  PREF sailor2/sea-ultrafeedback-onpolicy (Vietnamese) train=800 eval=100
DPO beta=0.1 lr=5e-06 epochs=1.0 loss=['sigmoid']

## 1. Mô hình đang học (policy) = SFT đã gộp + LoRA mới

Không có mô hình thứ hai trong VRAM. Log-prob của reference được tính một lần
trước khi huấn luyện (lúc LoRA còn bằng 0) rồi lưu lại, nên phần VRAM tăng thêm so
với SFT chủ yếu đến từ việc giữ cả câu chosen lẫn rejected trong một batch.

In [2]:
model, tokenizer = MD.load_model(C.SFT_MERGED)
model = MD.add_lora(model)

from datasets import Dataset

train_ds = Dataset.from_parquet(str(C.PREF_DIR / "train.parquet"))
eval_ds = Dataset.from_parquet(str(C.PREF_DIR / "eval.parquet"))
print(f"train={len(train_ds)} eval={len(eval_ds)}  columns={train_ds.column_names}")

==((====))==  Unsloth 2026.10.2: Fast Qwen3 patching. Transformers: 5.17.0.
   \\   /|    NVIDIA GeForce RTX 3050 Ti Laptop GPU. Num GPUs = 1. Max memory: 4.0 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu118. CUDA: 8.6. CUDA Toolkit: 11.8. Triton: 3.3.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

Loading weights:   0%|          | 1/310 [00:22<1:53:28, 22.03s/it]

Loading weights:   1%|          | 3/310 [00:22<30:13,  5.91s/it]

Loading weights:   1%|▏         | 4/310 [00:22<20:24,  4.00s/it]

Loading weights:   2%|▏         | 5/310 [00:23<14:15,  2.81s/it]

Loading weights:   3%|▎         | 8/310 [00:23<05:57,  1.18s/it]

Loading weights:   3%|▎         | 10/310 [00:23<04:02,  1.24it/s]

Loading weights:   4%|▍         | 12/310 [00:24<03:00,  1.65it/s]

Loading weights:   5%|▍         | 14/310 [00:24<02:17,  2.15it/s]

Loading weights:   5%|▍         | 15/310 [00:24<02:12,  2.23it/s]

Loading weights:   5%|▌         | 16/310 [00:25<02:08,  2.28it/s]

Loading weights:   6%|▌         | 19/310 [00:25<01:12,  4.02it/s]

Loading weights:   7%|▋         | 21/310 [00:25<00:59,  4.87it/s]

Loading weights:   7%|▋         | 23/310 [00:25<00:54,  5.22it/s]

Loading weights:   8%|▊         | 25/310 [00:26<00:54,  5.22it/s]

Loading weights:   8%|▊         | 26/310 [00:26<01:03,  4.44it/s]

Loading weights:   9%|▊         | 27/310 [00:27<01:14,  3.82it/s]

Loading weights:  10%|▉         | 30/310 [00:27<00:45,  6.14it/s]

Loading weights:  10%|█         | 31/310 [00:27<00:52,  5.34it/s]

Loading weights:  11%|█         | 33/310 [00:27<00:48,  5.75it/s]

Loading weights:  11%|█         | 34/310 [00:28<00:47,  5.76it/s]

Loading weights:  12%|█▏        | 36/310 [00:28<00:50,  5.39it/s]

Loading weights:  12%|█▏        | 37/310 [00:28<00:58,  4.63it/s]

Loading weights:  12%|█▏        | 38/310 [00:29<01:10,  3.84it/s]

Loading weights:  13%|█▎        | 41/310 [00:29<00:40,  6.62it/s]

Loading weights:  14%|█▍        | 43/310 [00:29<00:37,  7.17it/s]

Loading weights:  15%|█▍        | 45/310 [00:29<00:40,  6.52it/s]

Loading weights:  15%|█▌        | 47/310 [00:30<00:48,  5.47it/s]

Loading weights:  15%|█▌        | 48/310 [00:30<00:54,  4.77it/s]

Loading weights:  16%|█▌        | 49/310 [00:31<01:00,  4.30it/s]

Loading weights:  17%|█▋        | 52/310 [00:31<00:37,  6.80it/s]

Loading weights:  17%|█▋        | 53/310 [00:31<00:42,  6.00it/s]

Loading weights:  18%|█▊        | 55/310 [00:31<00:39,  6.42it/s]

Loading weights:  18%|█▊        | 56/310 [00:31<00:38,  6.62it/s]

Loading weights:  19%|█▊        | 58/310 [00:32<00:54,  4.62it/s]

Loading weights:  19%|█▉        | 59/310 [00:32<01:05,  3.84it/s]

Loading weights:  19%|█▉        | 60/310 [00:33<01:09,  3.61it/s]

Loading weights:  20%|██        | 63/310 [00:33<00:39,  6.27it/s]

Loading weights:  21%|██        | 65/310 [00:33<00:34,  7.04it/s]

Loading weights:  22%|██▏       | 67/310 [00:33<00:36,  6.68it/s]

Loading weights:  22%|██▏       | 69/310 [00:34<00:38,  6.33it/s]

Loading weights:  23%|██▎       | 70/310 [00:34<00:44,  5.39it/s]

Loading weights:  23%|██▎       | 71/310 [00:35<00:56,  4.21it/s]

Loading weights:  24%|██▍       | 74/310 [00:35<00:35,  6.67it/s]

Loading weights:  24%|██▍       | 75/310 [00:35<00:40,  5.85it/s]

Loading weights:  25%|██▍       | 77/310 [00:35<00:36,  6.37it/s]

Loading weights:  25%|██▌       | 78/310 [00:35<00:35,  6.56it/s]

Loading weights:  26%|██▌       | 80/310 [00:36<00:38,  5.99it/s]

Loading weights:  26%|██▌       | 81/310 [00:36<00:47,  4.78it/s]

Loading weights:  26%|██▋       | 82/310 [00:37<00:56,  4.01it/s]

Loading weights:  27%|██▋       | 85/310 [00:37<00:32,  6.87it/s]

Loading weights:  28%|██▊       | 87/310 [00:37<00:31,  7.14it/s]

Loading weights:  29%|██▊       | 89/310 [00:37<00:35,  6.14it/s]

Loading weights:  29%|██▉       | 91/310 [00:38<00:36,  5.97it/s]

Loading weights:  30%|██▉       | 92/310 [00:38<00:46,  4.69it/s]

Loading weights:  30%|███       | 93/310 [00:38<00:53,  4.09it/s]

Loading weights:  31%|███       | 96/310 [00:39<00:34,  6.18it/s]

Loading weights:  31%|███▏      | 97/310 [00:39<00:37,  5.70it/s]

Loading weights:  32%|███▏      | 99/310 [00:39<00:31,  6.60it/s]

Loading weights:  32%|███▏      | 100/310 [00:39<00:30,  6.87it/s]

Loading weights:  33%|███▎      | 102/310 [00:40<00:35,  5.92it/s]

Loading weights:  33%|███▎      | 103/310 [00:40<00:46,  4.44it/s]

Loading weights:  34%|███▎      | 104/310 [00:40<00:52,  3.91it/s]

Loading weights:  35%|███▍      | 107/310 [00:41<00:30,  6.59it/s]

Loading weights:  35%|███▌      | 109/310 [00:41<00:28,  6.93it/s]

Loading weights:  35%|███▌      | 110/310 [00:41<00:31,  6.28it/s]

Loading weights:  36%|███▋      | 113/310 [00:41<00:30,  6.47it/s]

Loading weights:  37%|███▋      | 114/310 [00:42<00:41,  4.77it/s]

Loading weights:  37%|███▋      | 115/310 [00:42<00:49,  3.92it/s]

Loading weights:  38%|███▊      | 118/310 [00:43<00:30,  6.36it/s]

Loading weights:  39%|███▊      | 120/310 [00:43<00:27,  6.93it/s]

Loading weights:  39%|███▉      | 121/310 [00:43<00:30,  6.16it/s]

Loading weights:  39%|███▉      | 122/310 [00:43<00:29,  6.42it/s]

Loading weights:  40%|████      | 124/310 [00:44<00:31,  5.87it/s]

Loading weights:  40%|████      | 125/310 [00:44<00:47,  3.93it/s]

Loading weights:  41%|████      | 126/310 [00:45<00:55,  3.31it/s]

Loading weights:  42%|████▏     | 129/310 [00:45<00:32,  5.52it/s]

Loading weights:  42%|████▏     | 130/310 [00:45<00:37,  4.81it/s]

Loading weights:  43%|████▎     | 132/310 [00:45<00:31,  5.71it/s]

Loading weights:  43%|████▎     | 133/310 [00:45<00:29,  6.10it/s]

Loading weights:  44%|████▎     | 135/310 [00:46<00:29,  5.88it/s]

Loading weights:  44%|████▍     | 136/310 [00:46<00:35,  4.90it/s]

Loading weights:  44%|████▍     | 137/310 [00:46<00:40,  4.25it/s]

Loading weights:  45%|████▌     | 140/310 [00:47<00:23,  7.23it/s]

Loading weights:  46%|████▌     | 142/310 [00:47<00:22,  7.54it/s]

Loading weights:  46%|████▋     | 144/310 [00:47<00:25,  6.60it/s]

Loading weights:  47%|████▋     | 146/310 [00:48<00:27,  6.07it/s]

Loading weights:  47%|████▋     | 147/310 [00:48<00:32,  4.95it/s]

Loading weights:  48%|████▊     | 148/310 [00:48<00:38,  4.25it/s]

Loading weights:  49%|████▊     | 151/310 [00:48<00:23,  6.89it/s]

Loading weights:  49%|████▉     | 153/310 [00:49<00:24,  6.53it/s]

Loading weights:  50%|████▉     | 154/310 [00:49<00:26,  5.83it/s]

Loading weights:  50%|█████     | 155/310 [00:49<00:24,  6.30it/s]

Loading weights:  51%|█████     | 157/310 [00:49<00:24,  6.18it/s]

Loading weights:  51%|█████     | 158/310 [00:50<00:35,  4.33it/s]

Loading weights:  51%|█████▏    | 159/310 [00:50<00:39,  3.81it/s]

Loading weights:  52%|█████▏    | 162/310 [00:50<00:22,  6.64it/s]

Loading weights:  53%|█████▎    | 164/310 [00:51<00:20,  7.17it/s]

Loading weights:  54%|█████▎    | 166/310 [00:51<00:24,  5.99it/s]

Loading weights:  54%|█████▍    | 168/310 [00:52<00:26,  5.26it/s]

Loading weights:  55%|█████▍    | 169/310 [00:52<00:32,  4.31it/s]

Loading weights:  55%|█████▍    | 170/310 [00:53<00:41,  3.38it/s]

Loading weights:  56%|█████▌    | 173/310 [00:53<00:24,  5.54it/s]

Loading weights:  56%|█████▌    | 174/310 [00:53<00:29,  4.68it/s]

Loading weights:  57%|█████▋    | 176/310 [00:53<00:24,  5.50it/s]

Loading weights:  57%|█████▋    | 177/310 [00:53<00:22,  5.97it/s]

Loading weights:  58%|█████▊    | 179/310 [00:54<00:22,  5.80it/s]

Loading weights:  58%|█████▊    | 180/310 [00:54<00:26,  4.85it/s]

Loading weights:  58%|█████▊    | 181/310 [00:55<00:32,  3.95it/s]

Loading weights:  59%|█████▉    | 184/310 [00:55<00:19,  6.57it/s]

Loading weights:  60%|█████▉    | 185/310 [00:55<00:22,  5.58it/s]

Loading weights:  60%|██████    | 187/310 [00:55<00:18,  6.50it/s]

Loading weights:  61%|██████    | 188/310 [00:55<00:17,  6.82it/s]

Loading weights:  61%|██████▏   | 190/310 [00:56<00:18,  6.58it/s]

Loading weights:  62%|██████▏   | 191/310 [00:56<00:23,  5.10it/s]

Loading weights:  62%|██████▏   | 192/310 [00:56<00:27,  4.36it/s]

Loading weights:  63%|██████▎   | 195/310 [00:56<00:15,  7.40it/s]

Loading weights:  64%|██████▎   | 197/310 [00:57<00:14,  7.80it/s]

Loading weights:  64%|██████▍   | 199/310 [00:57<00:16,  6.79it/s]

Loading weights:  65%|██████▍   | 201/310 [00:58<00:19,  5.54it/s]

Loading weights:  65%|██████▌   | 202/310 [00:58<00:23,  4.53it/s]

Loading weights:  65%|██████▌   | 203/310 [00:58<00:26,  4.09it/s]

Loading weights:  66%|██████▋   | 206/310 [00:58<00:15,  6.79it/s]

Loading weights:  67%|██████▋   | 208/310 [00:59<00:15,  6.44it/s]

Loading weights:  67%|██████▋   | 209/310 [00:59<00:18,  5.59it/s]

Loading weights:  68%|██████▊   | 210/310 [00:59<00:16,  5.98it/s]

Loading weights:  68%|██████▊   | 212/310 [01:00<00:16,  6.01it/s]

Loading weights:  69%|██████▊   | 213/310 [01:00<00:22,  4.23it/s]

Loading weights:  69%|██████▉   | 214/310 [01:00<00:24,  3.85it/s]

Loading weights:  70%|███████   | 217/310 [01:00<00:13,  6.66it/s]

Loading weights:  71%|███████   | 219/310 [01:01<00:12,  7.11it/s]

Loading weights:  71%|███████▏  | 221/310 [01:01<00:13,  6.43it/s]

Loading weights:  72%|███████▏  | 223/310 [01:02<00:15,  5.70it/s]

Loading weights:  72%|███████▏  | 224/310 [01:02<00:18,  4.58it/s]

Loading weights:  73%|███████▎  | 225/310 [01:02<00:22,  3.79it/s]

Loading weights:  74%|███████▎  | 228/310 [01:03<00:13,  6.11it/s]

Loading weights:  74%|███████▍  | 229/310 [01:03<00:14,  5.60it/s]

Loading weights:  75%|███████▍  | 231/310 [01:03<00:12,  6.28it/s]

Loading weights:  75%|███████▍  | 232/310 [01:03<00:12,  6.43it/s]

Loading weights:  75%|███████▌  | 234/310 [01:04<00:12,  6.26it/s]

Loading weights:  76%|███████▌  | 235/310 [01:04<00:14,  5.16it/s]

Loading weights:  76%|███████▌  | 236/310 [01:04<00:17,  4.18it/s]

Loading weights:  77%|███████▋  | 239/310 [01:04<00:10,  7.01it/s]

Loading weights:  78%|███████▊  | 241/310 [01:05<00:09,  7.58it/s]

Loading weights:  78%|███████▊  | 243/310 [01:05<00:10,  6.28it/s]

Loading weights:  79%|███████▉  | 245/310 [01:06<00:13,  4.88it/s]

Loading weights:  79%|███████▉  | 246/310 [01:06<00:15,  4.18it/s]

Loading weights:  80%|███████▉  | 247/310 [01:06<00:17,  3.70it/s]

Loading weights:  81%|████████  | 250/310 [01:07<00:09,  6.19it/s]

Loading weights:  81%|████████▏ | 252/310 [01:07<00:09,  6.30it/s]

Loading weights:  82%|████████▏ | 253/310 [01:07<00:10,  5.64it/s]

Loading weights:  82%|████████▏ | 254/310 [01:07<00:09,  5.77it/s]

Loading weights:  83%|████████▎ | 256/310 [01:08<00:10,  5.33it/s]

Loading weights:  83%|████████▎ | 257/310 [01:08<00:11,  4.52it/s]

Loading weights:  83%|████████▎ | 258/310 [01:08<00:13,  3.98it/s]

Loading weights:  84%|████████▍ | 261/310 [01:08<00:07,  6.85it/s]

Loading weights:  85%|████████▍ | 263/310 [01:09<00:06,  6.87it/s]

Loading weights:  85%|████████▌ | 264/310 [01:09<00:07,  5.79it/s]

Loading weights:  85%|████████▌ | 265/310 [01:09<00:07,  6.00it/s]

Loading weights:  86%|████████▌ | 267/310 [01:10<00:07,  5.92it/s]

Loading weights:  86%|████████▋ | 268/310 [01:10<00:09,  4.20it/s]

Loading weights:  87%|████████▋ | 269/310 [01:10<00:10,  3.79it/s]

Loading weights:  88%|████████▊ | 272/310 [01:11<00:05,  6.51it/s]

Loading weights:  88%|████████▊ | 274/310 [01:11<00:05,  7.02it/s]

Loading weights:  89%|████████▊ | 275/310 [01:11<00:05,  6.25it/s]

Loading weights:  89%|████████▉ | 276/310 [01:11<00:05,  6.66it/s]

Loading weights:  90%|████████▉ | 278/310 [01:12<00:05,  5.76it/s]

Loading weights:  90%|█████████ | 279/310 [01:12<00:06,  4.58it/s]

Loading weights:  90%|█████████ | 280/310 [01:12<00:07,  3.89it/s]

Loading weights:  91%|█████████▏| 283/310 [01:12<00:04,  6.48it/s]

Loading weights:  92%|█████████▏| 284/310 [01:13<00:04,  5.81it/s]

Loading weights:  92%|█████████▏| 286/310 [01:13<00:03,  6.55it/s]

Loading weights:  93%|█████████▎| 287/310 [01:13<00:03,  6.92it/s]

Loading weights:  93%|█████████▎| 289/310 [01:13<00:03,  6.40it/s]

Loading weights:  94%|█████████▎| 290/310 [01:14<00:03,  5.09it/s]

Loading weights:  94%|█████████▍| 291/310 [01:14<00:04,  4.55it/s]

Loading weights:  95%|█████████▍| 294/310 [01:14<00:02,  7.60it/s]

Loading weights:  95%|█████████▌| 296/310 [01:14<00:01,  7.96it/s]

Loading weights:  96%|█████████▌| 298/310 [01:15<00:01,  6.55it/s]

Loading weights:  97%|█████████▋| 300/310 [01:15<00:01,  6.04it/s]

Loading weights:  97%|█████████▋| 301/310 [01:16<00:01,  5.01it/s]

Loading weights:  97%|█████████▋| 302/310 [01:16<00:01,  4.28it/s]

Loading weights:  98%|█████████▊| 305/310 [01:16<00:00,  7.03it/s]

Loading weights:  99%|█████████▉| 307/310 [01:16<00:00,  7.46it/s]

Loading weights: 100%|█████████▉| 309/310 [01:17<00:00,  7.12it/s]

Loading weights: 100%|██████████| 310/310 [01:17<00:00,  4.02it/s]

The tokenizer you are loading from '/lab/models/sft-merged' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

The tokenizer you are loading from '/lab/models/sft-merged' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

Unsloth 2026.10.2 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

train=800 eval=100  columns=['prompt', 'chosen', 'rejected', 'chat_template_kwargs']

## 2. Huấn luyện

In [3]:
from trl import DPOTrainer

args = MD.dpo_config(C.ADAPTERS / "dpo-checkpoints")
print(f"loss_type={args.loss_type} beta={args.beta} lr={args.learning_rate} "
      f"precompute_ref={args.precompute_ref_log_probs} max_length={args.max_length}")

trainer = DPOTrainer(
    model=model,
    ref_model=None,
    args=args,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    processing_class=tokenizer,
)
torch.cuda.reset_peak_memory_stats()
training_started = time.perf_counter()
save_on_cpu = os.environ.get("DPO_SAVE_ON_CPU", "0") == "1"
with torch.autograd.graph.save_on_cpu(pin_memory=True) if save_on_cpu else nullcontext():
    result = trainer.train()
train_seconds = time.perf_counter() - training_started
final_eval = trainer.evaluate()
print(f"train loss {result.training_loss:.4f} · held-out reward accuracy "
      f"{final_eval.get('eval_rewards/accuracies', float('nan')):.3f}")

Unsloth: reducing dataset_num_proc 8 -> 2 to fit free memory (~1GB per worker). Set UNSLOTH_DATASET_NUM_PROC to override.
loss_type=['sigmoid'] beta=0.1 lr=5e-06 precompute_ref=True max_length=768

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 800 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 10,092,544 of 616,235,008 (1.64% trained)

Unsloth: Will smartly offload gradients to save VRAM!

Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

train loss 0.6887 · held-out reward accuracy 0.610

## 3. Đường cong reward (sản phẩm nộp `03-dpo-reward-curves.png`)

Implicit reward = β·log(π/π_ref) nên bắt đầu ở 0. Đọc đường *chosen*, không chỉ margin:
- chosen ↑, rejected ↓ → đúng ý đồ;
- chosen ↓, rejected ↓ nhanh hơn → **likelihood displacement** (Razin et al. 2024).

Loss ở bước đầu phải gần 0.693 (NB0 §3). Nếu không, reference đang sai.

In [4]:
train_hist = MD.reward_history(trainer.state.log_history)
eval_hist = MD.reward_history(trainer.state.log_history, prefix="eval_")
title = f"DPO · {C.COMPUTE_TIER} · β={C.DPO_BETA} · lr={C.DPO_LR} · {'+'.join(C.DPO_LOSS)}"
MD.plot_rewards(train_hist, eval_hist, title, C.SCREENSHOTS / "03-dpo-reward-curves.png")

first_loss = next((r["loss"] for r in trainer.state.log_history if "loss" in r), None)
print(f"first logged loss: {first_loss}")

first logged loss: 0.6871114730834961

In [5]:
label, message = MD.diagnose(eval_hist if len(eval_hist) >= 2 else train_hist)
print(f"[{label}] {message}")

[INTENDED] Chosen +0.147 up, rejected +0.090, margin +0.057.

## 4. Lưu adapter + metrics

In [6]:
import json

trainer.model.save_pretrained(str(C.DPO_ADAPTER))
tokenizer.save_pretrained(str(C.DPO_ADAPTER))
D.save_split_fingerprint(C.PREF_DIR, C.DPO_ADAPTER)  # NB4 refuses a held-out set this adapter saw


def last(df, col):
    return float(df[col].iloc[-1]) if not df.empty and col in df else None


metrics = {
    "compute_tier": C.COMPUTE_TIER,
    "base_model": C.BASE_MODEL,
    "reference": "models/sft-merged (precomputed)",
    "pref_dataset": C.PREF_DATASET,
    "beta": C.DPO_BETA,
    "lr": C.DPO_LR,
    "loss_type": C.DPO_LOSS,
    "epochs": C.DPO_EPOCHS,
    "train_pairs": len(train_ds),
    "eval_pairs": len(eval_ds),
    "max_length": C.MAX_LEN,
    "seed": C.SEED,
    "train_seconds": train_seconds,
    "peak_vram_gb": torch.cuda.max_memory_allocated() / 1024**3,
    "optimizer_steps": trainer.state.global_step,
    "saved_tensors_on_cpu": save_on_cpu,
    "log_history": trainer.state.log_history,
    "final_train_loss": float(result.training_loss),
    "first_logged_loss": first_loss,
    "end_chosen_reward": last(train_hist, "rewards/chosen"),
    "end_rejected_reward": last(train_hist, "rewards/rejected"),
    "end_reward_gap": last(train_hist, "rewards/margins"),
    "eval_chosen_reward": final_eval.get("eval_rewards/chosen"),
    "eval_rejected_reward": final_eval.get("eval_rewards/rejected"),
    "eval_reward_gap": final_eval.get("eval_rewards/margins"),
    "eval_reward_accuracy": final_eval.get("eval_rewards/accuracies"),
    "diagnosis": label,
}
(C.DPO_ADAPTER / "dpo_metrics.json").write_text(json.dumps(metrics, indent=2))
print(json.dumps(metrics, indent=2))

Unsloth: Restored added_tokens_decoder metadata in /lab/adapters/dpo/tokenizer_config.json.

{
  "compute_tier": "T4",
  "base_model": "Qwen/Qwen3-0.6B",
  "reference": "models/sft-merged (precomputed)",
  "pref_dataset": "sailor2/sea-ultrafeedback-onpolicy",
  "beta": 0.1,
  "lr": 5e-06,
  "loss_type": [
    "sigmoid"
  ],
  "epochs": 1.0,
  "train_pairs": 800,
  "eval_pairs": 100,
  "max_length": 768,
  "seed": 42,
  "train_seconds": 1316.970919334,
  "peak_vram_gb": 3.316309928894043,
  "optimizer_steps": 100,
  "saved_tensors_on_cpu": true,
  "log_history": [
    {
      "loss": 0.6871114730834961,
      "grad_norm": 17.401988983154297,
      "learning_rate": 2.0000000000000003e-06,
      "entropy": 1.9408343613147736,
      "num_tokens": 26931.0,
      "logits/chosen": -2.6503197402894654,
      "logits/rejected": -2.5814556601542065,
      "mean_token_accuracy": 0.563360869139433,
      "rewards/chosen": 0.03012734481599182,
      "rewards/rejected": 0.005733479859190993,
      "rewards/accuracies": 0.475,
      "rewards/margins": 0.02439386521000415,
      "logps/chosen": -408.9799765586853,
      "logps/rejected": -379.4004776954651,
      "epoch": 0.05,
      "step": 5
    },
    {
      "loss": 0.719652509689331,
      "grad_norm": 16.424732208251953,
      "learning_rate": 4.5e-06,
      "entropy": 1.724100537598133,
      "num_tokens": 55277.0,
      "logits/chosen": -2.561974670513314,
      "logits/rejected": -2.4255023386165524,
      "mean_token_accuracy": 0.6030196093022824,
      "rewards/chosen": -0.01845857175067067,
      "rewards/rejected": 0.027194981501088476,
      "rewards/accuracies": 0.375,
      "rewards/margins": -0.04565355291124433,
      "logps/chosen": -351.8302888393402,
      "logps/rejected": -318.64484705924986,
      "epoch": 0.1,
      "step": 10
    },
    {
      "loss": 0.6777982711791992,
      "grad_norm": 13.43253231048584,
      "learning_rate": 4.975670171853926e-06,
      "entropy": 1.8843366622924804,
      "num_tokens": 80880.0,
      "logits/chosen": -2.4617600734292786,
      "logits/rejected": -2.510389364932695,
      "mean_token_accuracy": 0.5751076381653547,
      "rewards/chosen": 0.024544773512752728,
      "rewards/rejected": -0.012471084418939427,
      "rewards/accuracies": 0.55,
      "rewards/margins": 0.0370158574776724,
      "logps/chosen": -365.12642726898196,
      "logps/rejected": -317.49033584594724,
      "epoch": 0.15,
      "step": 15
    },
    {
      "loss": 0.6977702140808105,
      "grad_norm": 10.950336456298828,
      "learning_rate": 4.8776412907378845e-06,
      "entropy": 1.7571416720747948,
      "num_tokens": 113901.0,
      "logits/chosen": -2.5883179642702703,
      "logits/rejected": -2.5346487680767056,
      "mean_token_accuracy": 0.5693074554204941,
      "rewards/chosen": 0.027073102764552458,
      "rewards/rejected": 0.029970083956141026,
      "rewards/accuracies": 0.575,
      "rewards/margins": -0.0028969827922992407,
      "logps/chosen": -486.0698939800262,
      "logps/rejected": -429.92061166763307,
      "epoch": 0.2,
      "step": 20
    },
    {
      "loss": 0.6975211143493653,
      "grad_norm": 19.676734924316406,
      "learning_rate": 4.707368982147318e-06,
      "entropy": 1.9057625725865364,
      "num_tokens": 145434.0,
      "logits/chosen": -2.4975297777841323,
      "logits/rejected": -2.3938158585936784,
      "mean_token_accuracy": 0.5747116357088089,
      "rewards/chosen": 0.03137610008125193,
      "rewards/rejected": 0.027407933487847914,
      "rewards/accuracies": 0.475,
      "rewards/margins": 0.003968166769482195,
      "logps/chosen": -528.4987390041351,
      "logps/rejected": -441.7165456771851,
      "epoch": 0.25,
      "step": 25
    },
    {
      "eval_loss": 0.6844313740730286,
      "eval_runtime": 29.9151,
      "eval_samples_per_second": 3.343,
      "eval_steps_per_second": 3.343,
      "eval_entropy": 1.8415001401305198,
      "eval_num_tokens": 145434.0,
      "eval_logits/chosen": -2.6208119536303753,
      "eval_logits/rejected": -2.5989339819984205,
      "eval_mean_token_accuracy": 0.5716992248594761,
      "eval_rewards/chosen": 0.04923435119286296,
      "eval_rewards/rejected": 0.023134283332328778,
      "eval_rewards/accuracies": 0.53,
      "eval_rewards/margins": 0.026100067878141998,
      "eval_logps/chosen": -491.5650002479553,
      "eval_logps/rejected": -403.99678216934205,
      "epoch": 0.25,
      "step": 25
    },
    {
      "loss": 0.6842894077301025,
      "grad_norm": 12.933697700500488,
      "learning_rate": 4.470026884016805e-06,
      "entropy": 1.8457377448678016,
      "num_tokens": 172627.0,
      "logits/chosen": -2.690847200349755,
      "logits/rejected": -2.6815728639368026,
      "mean_token_accuracy": 0.5802008420228958,
      "rewards/chosen": 0.019134707126067952,
      "rewards/rejected": -0.0015997070986486506,
      "rewards/accuracies": 0.575,
      "rewards/margins": 0.02073441430693492,
      "logps/chosen": -398.7406841754913,
      "logps/rejected": -341.56755957603457,
      "epoch": 0.3,
      "step": 30
    },
    {
      "loss": 0.6710278034210205,
      "grad_norm": 13.127522468566895,
      "learning_rate": 4.172826515897146e-06,
      "entropy": 1.782045418024063,
      "num_tokens": 199788.0,
      "logits/chosen": -2.601579075436779,
      "logits/rejected": -2.4285361104607133,
      "mean_token_accuracy": 0.5928212180733681,
      "rewards/chosen": 0.0525891688419506,
      "rewards/rejected": 0.0004187876242212951,
      "rewards/accuracies": 0.65,
      "rewards/margins": 0.052170381182804704,
      "logps/chosen": -416.85535831451415,
      "logps/rejected": -302.2590933799744,
      "epoch": 0.35,
      "step": 35
    },
    {
      "loss": 0.7014158248901368,
      "grad_norm": 11.335213661193848,
      "learning_rate": 3.824798160583012e-06,
      "entropy": 1.7685016691684723,
      "num_tokens": 225663.0,
      "logits/chosen": -2.524599917260468,
      "logits/rejected": -2.5147969023283685,
      "mean_token_accuracy": 0.5860059909522534,
      "rewards/chosen": 0.02696639658533968,
      "rewards/rejected": 0.03811483872123063,
      "rewards/accuracies": 0.475,
      "rewards/margins": -0.011148441839031875,
      "logps/chosen": -331.2264297962189,
      "logps/rejected": -275.6329141139984,
      "epoch": 0.4,
      "step": 40
    },
    {
      "loss": 0.6800529479980468,
      "grad_norm": 13.419501304626465,
      "learning_rate": 3.436516483539781e-06,
      "entropy": 1.7025733396410943,
      "num_tokens": 252199.0,
      "logits/chosen": -2.721350511849395,
      "logits/rejected": -2.6739155671026507,
      "mean_token_accuracy": 0.6128586202859878,
      "rewards/chosen": 0.09444153516669758,
      "rewards/rejected": 0.05862667161272839,
      "rewards/accuracies": 0.65,
      "rewards/margins": 0.03581486319890246,
      "logps/chosen": -408.76183466911317,
      "logps/rejected": -334.535608291626,
      "epoch": 0.45,
      "step": 45
    },
    {
      "loss": 0.6804295539855957,
      "grad_norm": 11.228517532348633,
      "learning_rate": 3.019779227044398e-06,
      "entropy": 1.7190893471240998,
      "num_tokens": 278676.0,
      "logits/chosen": -2.5329251578074152,
      "logits/rejected": -2.5061649304204527,
      "mean_token_accuracy": 0.5981312625110149,
      "rewards/chosen": 0.06929487767047249,
      "rewards/rejected": 0.040034743363503364,
      "rewards/accuracies": 0.65,
      "rewards/margins": 0.029260134347714482,
      "logps/chosen": -368.05392622947693,
      "logps/rejected": -333.9652775764465,
      "epoch": 0.5,
      "step": 50
    },
    {
      "eval_loss": 0.6760250329971313,
      "eval_runtime": 29.663,
      "eval_samples_per_second": 3.371,
      "eval_steps_per_second": 3.371,
      "eval_entropy": 1.8420793828368187,
      "eval_num_tokens": 278676.0,
      "eval_logits/chosen": -2.6239296588536636,
      "eval_logits/rejected": -2.601755855197423,
      "eval_mean_token_accuracy": 0.5709929782152176,
      "eval_rewards/chosen": 0.10460259049898013,
      "eval_rewards/rejected": 0.061296727448352614,
      "eval_rewards/accuracies": 0.52,
      "eval_rewards/margins": 0.043305862264242025,
      "eval_logps/chosen": -491.01131786346434,
      "eval_logps/rejected": -403.6151577377319,
      "epoch": 0.5,
      "step": 50
    },
    {
      "loss": 0.6926483631134033,
      "grad_norm": 15.287433624267578,
      "learning_rate": 2.587248741756253e-06,
      "entropy": 1.8745093062520026,
      "num_tokens": 304798.0,
      "logits/chosen": -2.4833894568649635,
      "logits/rejected": -2.3861998046215316,
      "mean_token_accuracy": 0.5852631837129593,
      "rewards/chosen": 0.06133004524745047,
      "rewards/rejected": 0.05894008713949006,
      "rewards/accuracies": 0.475,
      "rewards/margins": 0.002389958291314542,
      "logps/chosen": -364.07107455730437,
      "logps/rejected": -274.30356788635254,
      "epoch": 0.55,
      "step": 55
    },
    {
      "loss": 0.6914795875549317,
      "grad_norm": 19.90397071838379,
      "learning_rate": 2.1520672475998374e-06,
      "entropy": 1.8259922698140145,
      "num_tokens": 334804.0,
      "logits/chosen": -2.557132336341252,
      "logits/rejected": -2.554270159257153,
      "mean_token_accuracy": 0.5845383852720261,
      "rewards/chosen": 0.10805860394857518,
      "rewards/rejected": 0.09862798365284106,
      "rewards/accuracies": 0.575,
      "rewards/margins": 0.009430619608610868,
      "logps/chosen": -420.1217577457428,
      "logps/rejected": -400.2637201786041,
      "epoch": 0.6,
      "step": 60
    },
    {
      "loss": 0.6736061096191406,
      "grad_norm": 14.486200332641602,
      "learning_rate": 1.7274575140626318e-06,
      "entropy": 1.9875581577420234,
      "num_tokens": 362214.0,
      "logits/chosen": -2.746073893207738,
      "logits/rejected": -2.6980238465599458,
      "mean_token_accuracy": 0.5428967349231243,
      "rewards/chosen": 0.15032802788773553,
      "rewards/rejected": 0.0980961158144055,
      "rewards/accuracies": 0.625,
      "rewards/margins": 0.05223191070836038,
      "logps/chosen": -594.1717197418213,
      "logps/rejected": -491.60028886795044,
      "epoch": 0.65,
      "step": 65
    },
    {
      "loss": 0.6951647281646729,
      "grad_norm": 20.539459228515625,
      "learning_rate": 1.3263210930352737e-06,
      "entropy": 1.8789862424135209,
      "num_tokens": 395060.0,
      "logits/chosen": -2.6504411713585885,
      "logits/rejected": -2.594043581055304,
      "mean_token_accuracy": 0.5692882046103478,
      "rewards/chosen": 0.14804830725770443,
      "rewards/rejected": 0.13187117749184835,
      "rewards/accuracies": 0.5,
      "rewards/margins": 0.016177129466086626,
      "logps/chosen": -644.1382669448852,
      "logps/rejected": -526.5469132423401,
      "epoch": 0.7,
      "step": 70
    },
    {
      "loss": 0.6707273483276367,
      "grad_norm": 15.354232788085938,
      "learning_rate": 9.608463116858544e-07,
      "entropy": 1.7895369231700897,
      "num_tokens": 423394.0,
      "logits/chosen": -2.659887133908711,
      "logits/rejected": -2.7092880175314766,
      "mean_token_accuracy": 0.5730747394263744,
      "rewards/chosen": 0.12515277187194443,
      "rewards/rejected": 0.07102000802697148,
      "rewards/accuracies": 0.625,
      "rewards/margins": 0.05413276279286947,
      "logps/chosen": -410.65472230911257,
      "logps/rejected": -352.0878468036652,
      "epoch": 0.75,
      "step": 75
    },
    {
      "eval_loss": 0.6649079322814941,
      "eval_runtime": 32.0677,
      "eval_samples_per_second": 3.118,
      "eval_steps_per_second": 3.118,
      "eval_entropy": 1.8414064583182335,
      "eval_num_tokens": 423394.0,
      "eval_logits/chosen": -2.624023681016132,
      "eval_logits/rejected": -2.601868080832036,
      "eval_mean_token_accuracy": 0.5708107277750969,
      "eval_rewards/chosen": 0.15281632689060642,
      "eval_rewards/rejected": 0.08355666811548872,
      "eval_rewards/accuracies": 0.64,
      "eval_rewards/margins": 0.06925965863745659,
      "eval_logps/chosen": -490.52918050765993,
      "eval_logps/rejected": -403.3925583267212,
      "epoch": 0.75,
      "step": 75
    },
    {
      "loss": 0.6906277656555175,
      "grad_norm": 12.006564140319824,
      "learning_rate": 6.421379363065142e-07,
      "entropy": 1.8988397911190986,
      "num_tokens": 449154.0,
      "logits/chosen": -2.624885559677544,
      "logits/rejected": -2.6608595652128266,
      "mean_token_accuracy": 0.5570188701152802,
      "rewards/chosen": 0.10890780653862749,
      "rewards/rejected": 0.09861694964929484,
      "rewards/accuracies": 0.65,
      "rewards/margins": 0.010290857404470444,
      "logps/chosen": -428.3015469551086,
      "logps/rejected": -389.0169555187225,
      "epoch": 0.8,
      "step": 80
    },
    {
      "loss": 0.6861607551574707,
      "grad_norm": 14.749383926391602,
      "learning_rate": 3.798797596089351e-07,
      "entropy": 1.6815166473388672,
      "num_tokens": 474941.0,
      "logits/chosen": -2.447302331592268,
      "logits/rejected": -2.370377489228408,
      "mean_token_accuracy": 0.6076013498008251,
      "rewards/chosen": 0.09756315859558526,
      "rewards/rejected": 0.07933961098315194,
      "rewards/accuracies": 0.5,
      "rewards/margins": 0.018223547749221324,
      "logps/chosen": -408.54624342918396,
      "logps/rejected": -350.3972289085388,
      "epoch": 0.85,
      "step": 85
    },
    {
      "loss": 0.6954971790313721,
      "grad_norm": 13.990935325622559,
      "learning_rate": 1.8204036358303173e-07,
      "entropy": 1.7639727547764779,
      "num_tokens": 503253.0,
      "logits/chosen": -2.5744169545492186,
      "logits/rejected": -2.536706423113855,
      "mean_token_accuracy": 0.5930213637650013,
      "rewards/chosen": 0.08167022263223771,
      "rewards/rejected": 0.0814707150333561,
      "rewards/accuracies": 0.625,
      "rewards/margins": 0.0001995078520849347,
      "logps/chosen": -401.6020477771759,
      "logps/rejected": -376.8009178638458,
      "epoch": 0.9,
      "step": 90
    },
    {
      "loss": 0.7030028343200684,
      "grad_norm": 13.85461139678955,
      "learning_rate": 5.463099816548578e-08,
      "entropy": 1.8696103230118752,
      "num_tokens": 528857.0,
      "logits/chosen": -2.586507926239789,
      "logits/rejected": -2.4852875120504345,
      "mean_token_accuracy": 0.5727432578802109,
      "rewards/chosen": 0.09547455006795644,
      "rewards/rejected": 0.10531532491149846,
      "rewards/accuracies": 0.625,
      "rewards/margins": -0.00984077503089793,
      "logps/chosen": -420.1733795166016,
      "logps/rejected": -397.30622177124025,
      "epoch": 0.95,
      "step": 95
    },
    {
      "loss": 0.67757568359375,
      "grad_norm": 15.753692626953125,
      "learning_rate": 1.5229324522605949e-09,
      "entropy": 1.8632775574922562,
      "num_tokens": 557774.0,
      "logits/chosen": -2.6219940507066557,
      "logits/rejected": -2.5409267103165964,
      "mean_token_accuracy": 0.585787070542574,
      "rewards/chosen": 0.10555085447267629,
      "rewards/rejected": 0.06821880910429172,
      "rewards/accuracies": 0.625,
      "rewards/margins": 0.03733204496093094,
      "logps/chosen": -446.95621023178103,
      "logps/rejected": -413.50531191825866,
      "epoch": 1.0,
      "step": 100
    },
    {
      "eval_loss": 0.6737457513809204,
      "eval_runtime": 33.7601,
      "eval_samples_per_second": 2.962,
      "eval_steps_per_second": 2.962,
      "eval_entropy": 1.8426579102873801,
      "eval_num_tokens": 557774.0,
      "eval_logits/chosen": -2.623602081961317,
      "eval_logits/rejected": -2.602575435346948,
      "eval_mean_token_accuracy": 0.5710846237838269,
      "eval_rewards/chosen": 0.14334984056651592,
      "eval_rewards/rejected": 0.09254212758271024,
      "eval_rewards/accuracies": 0.61,
      "eval_rewards/margins": 0.05080771384993568,
      "eval_logps/chosen": -490.6238453674316,
      "eval_logps/rejected": -403.30270374298095,
      "epoch": 1.0,
      "step": 100
    },
    {
      "train_runtime": 1312.4483,
      "train_samples_per_second": 0.61,
      "train_steps_per_second": 0.076,
      "total_flos": 1662953841229824.0,
      "train_loss": 0.6886779737472534,
      "epoch": 1.0,
      "step": 100
    },
    {
      "eval_loss": 0.6737457513809204,
      "eval_runtime": 30.9529,
      "eval_samples_per_second": 3.231,
      "eval_steps_per_second": 3.231,
      "eval_entropy": 1.8426579102873801,
      "eval_num_tokens": 557774.0,
      "eval_logits/chosen": -2.623602081961317,
      "eval_logits/rejected": -2.602575435346948,
      "eval_mean_token_accuracy": 0.5710846237838269,
      "eval_rewards/chosen": 0.14334984056651592,
      "eval_rewards/rejected": 0.09254212758271024,
      "eval_rewards/accuracies": 0.61,
      "eval_rewards/margins": 0.05080771384993568,
      "eval_logps/chosen": -490.6238453674316,
      "eval_logps/rejected": -403.30270374298095,
      "epoch": 1.0,
      "step": 100
    }
  ],
  "final_train_loss": 0.6886779737472534,
  "first_logged_loss": 0.6871114730834961,
  "end_chosen_reward": 0.10555085447267629,
  "end_rejected_reward": 0.06821880910429172,
  "end_reward_gap": 0.03733204496093094,
  "eval_chosen_reward": 0.14334984056651592,
  "eval_rejected_reward": 0.09254212758271024,
  "eval_reward_gap": 0.05080771384993568,
  "eval_reward_accuracy": 0.61,
  "diagnosis": "INTENDED"
}

## 5. Ghi chú vibe-coding: quét β (+6 độ chặt chẽ)

`make beta-sweep` chạy `scripts/train_dpo.py` với β ∈ {0.05, 0.1, 0.5} và lưu vào
`adapters/dpo-b*/`. `python scripts/eval_judge.py --plot-sweep` vẽ β theo margin held-out.

**Đoán trước khi xem:** β lớn giữ mô hình đang học (policy) gần reference hơn. Margin tính bằng β·log-ratio
sẽ thay đổi thế nào? Còn độ chính xác reward?

**Tiếp theo:** NB3b (so sánh RPO / SimPO-norm / LD-DPO / ORPO) hoặc NB4 (đánh giá).